[36mATRI[0m | 03-03 18:05:40 | ERROR plugin.manager >> Failed to import "nonebot_plugin_statistical"
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fe94766b040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fe94f7df130>
         │    └ <function MultiCommand.invoke at 0x7fe94766f0d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fe94f8b3d30>
           │               │       │       └ <function Command.invoke at 0x7fe94766baf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7fe94f8b3d30>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fe947eb8a60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7fe94f8b3d30>
           │   │      │    └ <function run at 0x7fe93e6b75e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7fe9478e88b0>
           └ <click.core.Context object at 0x7fe94f8b3d30>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7fe93e6a63a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
             │         │             └ 'bot'
             │         └ <function import_module at 0x7fe94f81f8b0>
             └ <module 'importlib' from '/usr/local/python3/lib/python3.8/importlib/__init__.py'>
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'bot'
           │          └ <function _gcd_import at 0x7fe94f94e430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./bot.py", line 29, in <module>
    nonebot.load_plugins("src/plugins")
    │       └ <function load_plugins at 0x7fe9454e73a0>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>

  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/load.py", line 39, in load_plugins
    return manager.load_all_plugins()
           │       └ <function PluginManager.load_all_plugins at 0x7fe9454d9ee0>
           └ <nonebot.plugin.manager.PluginManager object at 0x7fe93de9c5b0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 128, in load_all_plugins
    return set(
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
                  │    │           │         │       │    └ <function PluginManager.list_plugins at 0x7fe9454d9dc0>
                  │    │           │         │       └ <nonebot.plugin.manager.PluginManager object at 0x7fe93de9c5b0>
                  │    │           │         └ 'nonebot_plugin_statistical'
                  │    │           └ 'nonebot_plugin_statistical'
                  │    └ <function PluginManager.load_plugin at 0x7fe9454d9e50>
                  └ <nonebot.plugin.manager.PluginManager object at 0x7fe93de9c5b0>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 106, in load_plugin
    module = importlib.import_module(
             │         └ <function import_module at 0x7fe94f81f8b0>
             └ <module 'importlib' from '/usr/local/python3/lib/python3.8/importlib/__init__.py'>
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'src.plugins.nonebot_plugin_statistical'
           │          └ <function _gcd_import at 0x7fe94f94e430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 194, in exec_module
    super().exec_module(module)
                        └ <module 'src.plugins.nonebot_plugin_statistical' from './src/plugins/nonebot_plugin_statistical/__init__.py'>
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./src/plugins/nonebot_plugin_statistical/__init__.py", line 1, in <module>
    from .statistical_hook import *

  File "./src/plugins/nonebot_plugin_statistical/statistical_hook.py", line 7, in <module>
    from .config import save_data, get_prefix_group_count_dict, get_prefix_user_count_dict, \

  File "./src/plugins/nonebot_plugin_statistical/config.py", line 149, in <module>
    plugin2cmd: dict = json.load(f)
                       │    │    └ <_io.TextIOWrapper name='/root/Projects/Kori-Bot/Kori-bot/data/statistical/plugin2cmd.json' mode='r' encoding='utf8'>
                       │    └ <built-in function load>
                       └ <module 'ujson' from '/usr/local/python3/lib/python3.8/site-packages/ujson.cpython-38-x86_64-linux-gnu.so'>

ValueError: Expected object or value
[36mATRI[0m | 03-03 18:06:00 | ERROR apscheduler >> Job "memesfeiyu (trigger: cron[hour='18', minute='6'], next run at: 2022-03-04 18:06:00 CST)" raised an exception
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fe94766b040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fe94f7df130>
         │    └ <function MultiCommand.invoke at 0x7fe94766f0d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fe94f8b3d30>
           │               │       │       └ <function Command.invoke at 0x7fe94766baf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7fe94f8b3d30>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fe947eb8a60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7fe94f8b3d30>
           │   │      │    └ <function run at 0x7fe93e6b75e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7fe9478e88b0>
           └ <click.core.Context object at 0x7fe94f8b3d30>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7fe93e6a63a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7fe9407b0550>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7fe9407b00d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7fe93e4b4280>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7fe93e4b4670>
    └ <uvicorn.server.Server object at 0x7fe91d5f0e50>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fe93e4b4700>
           │       │   └ <uvicorn.server.Server object at 0x7fe91d5f0e50>
           │       └ <function run at 0x7fe943efe0d0>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fe91d5f9840>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   │   │     │   │       │   └ <member 'kwargs' of 'Job' objects>
                   │   │     │   │       └ <Job (id=12745 name=memesfeiyu)>
                   │   │     │   └ <member 'args' of 'Job' objects>
                   │   │     └ <Job (id=12745 name=memesfeiyu)>
                   │   └ <member 'func' of 'Job' objects>
                   └ <Job (id=12745 name=memesfeiyu)>

  File "./src/plugins/memes_from_feiyucans_space/__init__.py", line 24, in memesfeiyu
    msg = await suijitu()
                └ <function suijitu at 0x7fe91f7644c0>

  File "./src/plugins/memes_from_feiyucans_space/__init__.py", line 38, in suijitu
    now_timeArray = time.strptime(now_time, "%Y-%m-%d")
                    │             └ '2022-03-03'
                    └ {'HOUR': 7, 'MINUTE': 30}

AttributeError: 'dict' object has no attribute 'strptime'
[36mATRI[0m | 03-03 18:09:18 | ERROR nonebot >> Running matcher <Matcher from src.plugins.nonebot_plugin_heweather, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fe94766b040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fe94f7df130>
         │    └ <function MultiCommand.invoke at 0x7fe94766f0d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fe94f8b3d30>
           │               │       │       └ <function Command.invoke at 0x7fe94766baf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7fe94f8b3d30>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fe947eb8a60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7fe94f8b3d30>
           │   │      │    └ <function run at 0x7fe93e6b75e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7fe9478e88b0>
           └ <click.core.Context object at 0x7fe94f8b3d30>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7fe93e6a63a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7fe9407b0550>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7fe9407b00d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7fe93e4b4280>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7fe93e4b4670>
    └ <uvicorn.server.Server object at 0x7fe91d5f0e50>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fe93e4b4700>
           │       │   └ <uvicorn.server.Server object at 0x7fe91d5f0e50>
           │       └ <function run at 0x7fe943efe0d0>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fe91d5f9840>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0x7fe9407d2d30>: <Task finished name='Task-6980' coro=<_command() done, defined at /usr/local/python3/...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7fe91c108e80>
          │            │        │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None}, '_matched': '深圳天气', '_matched_groups': ('深圳',), '_ma...
          │            │        │    └ GroupMessageEvent(time=1646302157, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │            │        └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
          │            └ <Matcher from src.plugins.nonebot_plugin_heweather, type=message, priority=1, temp=False>
          └ <function _run_matcher at 0x7fe93e5d1280>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0x7fe9407d2d30>: <Task finished name='Task-6980' coro=<_command() done, defined at /usr/local/python3/...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7fe91c108e80>
          │       │   │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None}, '_matched': '深圳天气', '_matched_groups': ('深圳',), '_ma...
          │       │   │    └ GroupMessageEvent(time=1646302157, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
          │       └ <function Matcher.run at 0x7fe9407d2790>
          └ <Matcher from src.plugins.nonebot_plugin_heweather, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0x7fe9407d2d30>: <Task finished name='Task-6980' coro=<_command() done, defined at /usr/local/python3/...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7fe91c108e80>
          │    │          │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None}, '_matched': '深圳天气', '_matched_groups': ('深圳',), '_ma...
          │    │          │    └ GroupMessageEvent(time=1646302157, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
          │    └ <function Matcher.simple_run at 0x7fe9407d2700>
          └ <Matcher from src.plugins.nonebot_plugin_heweather, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function _ at 0x7fe91d7769d0>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='eve...
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'bot': <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>, 'event': GroupMessageEvent(time=1646302157, self_id=5...
                 │    └ <function _ at 0x7fe91d7769d0>
                 └ <Dependent call=<function _ at 0x7fe91d7769d0>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='eve...

  File "./src/plugins/nonebot_plugin_heweather/__init__.py", line 35, in _
    img = await render(w_data)
                │      └ <src.plugins.nonebot_plugin_heweather.weather_data.Weather object at 0x7fe91c98d520>
                └ <function render at 0x7fe91d783550>

  File "./src/plugins/nonebot_plugin_heweather/render_pic.py", line 11, in render
    return await template_to_pic(
                 └ <function template_to_pic at 0x7fe920d753a0>

  File "/usr/local/python3/lib/python3.8/site-packages/nonebot_plugin_htmlrender/date_source.py", line 194, in template_to_pic
    return await html_to_pic(
                 └ <function html_to_pic at 0x7fe920d75310>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot_plugin_htmlrender/date_source.py", line 159, in html_to_pic
    await page.goto(template_path)
          │    │    └ 'file://src/plugins/nonebot_plugin_heweather/templates'
          │    └ <function Page.goto at 0x7fe921070e50>
          └ <Page url='about:blank'>
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 7516, in goto
    await self._async(
          │    └ <function AsyncBase._async at 0x7fe9210b3670>
          └ <Page url='about:blank'>
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_page.py", line 487, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
                 │    │           │      └ <function locals_to_params at 0x7fe9213fd700>
                 │    │           └ <function Frame.goto at 0x7fe92110a550>
                 │    └ <Frame name= url='about:blank'>
                 └ <Page url='about:blank'>
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_frame.py", line 122, in goto
    await self._channel.send("goto", locals_to_params(locals()))
          │    │        │            └ <function locals_to_params at 0x7fe9213fd700>
          │    │        └ <function Channel.send at 0x7fe9213dfb80>
          │    └ <playwright._impl._connection.Channel object at 0x7fe91c05c520>
          └ <Frame name= url='about:blank'>
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
                 │    │          │       └ {'url': 'file://src/plugins/nonebot_plugin_heweather/templates'}
                 │    │          └ 'goto'
                 │    └ <function Channel.inner_send at 0x7fe9213d7820>
                 └ <playwright._impl._connection.Channel object at 0x7fe91c05c520>
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
                       └ {<Future finished exception=Error('net::ERR_INVALID_URL at file://src/plugins/nonebot_plugin_heweather/templates\n===========...

playwright._impl._api_types.Error: net::ERR_INVALID_URL at file://src/plugins/nonebot_plugin_heweather/templates
=========================== logs ===========================
navigating to "file://src/plugins/nonebot_plugin_heweather/templates", waiting until "load"
============================================================
[36mATRI[0m | 03-03 18:09:19 | ERROR nonebot >> Error when running RunPostProcessors
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fe94766b040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fe94f7df130>
         │    └ <function MultiCommand.invoke at 0x7fe94766f0d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fe94f8b3d30>
           │               │       │       └ <function Command.invoke at 0x7fe94766baf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7fe94f8b3d30>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fe947eb8a60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7fe94f8b3d30>
           │   │      │    └ <function run at 0x7fe93e6b75e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7fe9478e88b0>
           └ <click.core.Context object at 0x7fe94f8b3d30>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7fe93e6a63a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7fe9407b0550>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7fe9407b00d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7fe93e4b4280>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7fe93e4b4670>
    └ <uvicorn.server.Server object at 0x7fe91d5f0e50>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fe93e4b4700>
           │       │   └ <uvicorn.server.Server object at 0x7fe91d5f0e50>
           │       └ <function run at 0x7fe943efe0d0>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fe91d5f9840>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 227, in _run_matcher
    await asyncio.gather(*coros)
          │       │       └ [<coroutine object _run_coro_with_catch at 0x7fe91c13c4c0>]
          │       └ <function gather at 0x7fe941d22c10>
          └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 115, in _run_coro_with_catch
    return await coro
                 └ <coroutine object Dependent.__call__ at 0x7fe91c10c440>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'exception': Error('net::ERR_INVALID_URL at file://src/plugins/nonebot_plugin_heweather/templates\n=========================...
                 │    └ <function _track_error at 0x7fe939ae6820>
                 └ <Dependent call=<function _track_error at 0x7fe939ae6820>, params=[ModelField(name='exception', type=Optional[Exception], req...
  File "/usr/local/python3/lib/python3.8/site-packages/ATRI/exceptions.py", line 115, in _track_error
    await bot.send_private_msg(user_id=superusers, message=msg)
          │                            │                   └ '呜——出错了...追踪: 4LaSJCkZ'
          │                            └ '1234567890'
          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/bot.py", line 208, in call_api
    return await super().call_api(api, **data)
                                  │      └ {'user_id': '1234567890', 'message': '呜——出错了...追踪: 4LaSJCkZ'}
                                  └ 'send_private_msg'
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 117, in call_api
    raise exception
          └ <ActionFailed data=None, echo={'seq': 3}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
                   │    │       │         │     │      └ {'user_id': '1234567890', 'message': '呜——出错了...追踪: 4LaSJCkZ'}
                   │    │       │         │     └ 'send_private_msg'
                   │    │       │         └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
                   │    │       └ <function Adapter._call_api at 0x7fe93e5d1b80>
                   │    └ <nonebot.adapters.onebot.v11.adapter.Adapter object at 0x7fe93e6c04c0>
                   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 107, in _call_api
    return _handle_api_result(
           └ <function _handle_api_result at 0x7fe93e65f310>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/utils.py", line 81, in _handle_api_result
    raise ActionFailed(**result)
          │              └ {'data': None, 'echo': {'seq': 3}, 'msg': 'SEND_MSG_API_ERROR', 'retcode': 100, 'status': 'failed', 'wording': '请参考 go-cqhttp...
          └ <class 'nonebot.adapters.onebot.v11.exception.ActionFailed'>

nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 3}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
[36mATRI[0m | 03-03 18:09:31 | ERROR nonebot >> Running matcher <Matcher from src.plugins.nonebot_plugin_heweather, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fe94766b040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fe94f7df130>
         │    └ <function MultiCommand.invoke at 0x7fe94766f0d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fe94f8b3d30>
           │               │       │       └ <function Command.invoke at 0x7fe94766baf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7fe94f8b3d30>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fe947eb8a60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7fe94f8b3d30>
           │   │      │    └ <function run at 0x7fe93e6b75e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7fe9478e88b0>
           └ <click.core.Context object at 0x7fe94f8b3d30>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7fe93e6a63a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7fe9407b0550>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7fe9407b00d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7fe93e4b4280>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7fe93e4b4670>
    └ <uvicorn.server.Server object at 0x7fe91d5f0e50>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fe93e4b4700>
           │       │   └ <uvicorn.server.Server object at 0x7fe91d5f0e50>
           │       └ <function run at 0x7fe943efe0d0>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fe91d5f9840>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0x7fe9407d2d30>: <Task finished name='Task-7368' coro=<_command() done, defined at /usr/local/python3/...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7fe91c110af0>
          │            │        │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None}, '_matched': '/深圳天气', '_matched_groups': ('/深圳',), '_...
          │            │        │    └ GroupMessageEvent(time=1646302170, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │            │        └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
          │            └ <Matcher from src.plugins.nonebot_plugin_heweather, type=message, priority=1, temp=False>
          └ <function _run_matcher at 0x7fe93e5d1280>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0x7fe9407d2d30>: <Task finished name='Task-7368' coro=<_command() done, defined at /usr/local/python3/...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7fe91c110af0>
          │       │   │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None}, '_matched': '/深圳天气', '_matched_groups': ('/深圳',), '_...
          │       │   │    └ GroupMessageEvent(time=1646302170, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
          │       └ <function Matcher.run at 0x7fe9407d2790>
          └ <Matcher from src.plugins.nonebot_plugin_heweather, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0x7fe9407d2d30>: <Task finished name='Task-7368' coro=<_command() done, defined at /usr/local/python3/...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7fe91c110af0>
          │    │          │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None}, '_matched': '/深圳天气', '_matched_groups': ('/深圳',), '_...
          │    │          │    └ GroupMessageEvent(time=1646302170, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
          │    └ <function Matcher.simple_run at 0x7fe9407d2700>
          └ <Matcher from src.plugins.nonebot_plugin_heweather, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function _ at 0x7fe91d7769d0>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='eve...
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'bot': <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>, 'event': GroupMessageEvent(time=1646302170, self_id=5...
                 │    └ <function _ at 0x7fe91d7769d0>
                 └ <Dependent call=<function _ at 0x7fe91d7769d0>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='eve...

  File "./src/plugins/nonebot_plugin_heweather/__init__.py", line 35, in _
    img = await render(w_data)
                │      └ <src.plugins.nonebot_plugin_heweather.weather_data.Weather object at 0x7fe91c05c9a0>
                └ <function render at 0x7fe91d783550>

  File "./src/plugins/nonebot_plugin_heweather/render_pic.py", line 11, in render
    return await template_to_pic(
                 └ <function template_to_pic at 0x7fe920d753a0>

  File "/usr/local/python3/lib/python3.8/site-packages/nonebot_plugin_htmlrender/date_source.py", line 194, in template_to_pic
    return await html_to_pic(
                 └ <function html_to_pic at 0x7fe920d75310>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot_plugin_htmlrender/date_source.py", line 159, in html_to_pic
    await page.goto(template_path)
          │    │    └ 'file://src/plugins/nonebot_plugin_heweather/templates'
          │    └ <function Page.goto at 0x7fe921070e50>
          └ <Page url='about:blank'>
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 7516, in goto
    await self._async(
          │    └ <function AsyncBase._async at 0x7fe9210b3670>
          └ <Page url='about:blank'>
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_page.py", line 487, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
                 │    │           │      └ <function locals_to_params at 0x7fe9213fd700>
                 │    │           └ <function Frame.goto at 0x7fe92110a550>
                 │    └ <Frame name= url='about:blank'>
                 └ <Page url='about:blank'>
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_frame.py", line 122, in goto
    await self._channel.send("goto", locals_to_params(locals()))
          │    │        │            └ <function locals_to_params at 0x7fe9213fd700>
          │    │        └ <function Channel.send at 0x7fe9213dfb80>
          │    └ <playwright._impl._connection.Channel object at 0x7fe91c1211f0>
          └ <Frame name= url='about:blank'>
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
                 │    │          │       └ {'url': 'file://src/plugins/nonebot_plugin_heweather/templates'}
                 │    │          └ 'goto'
                 │    └ <function Channel.inner_send at 0x7fe9213d7820>
                 └ <playwright._impl._connection.Channel object at 0x7fe91c1211f0>
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
                       └ {<Future finished exception=Error('net::ERR_INVALID_URL at file://src/plugins/nonebot_plugin_heweather/templates\n===========...

playwright._impl._api_types.Error: net::ERR_INVALID_URL at file://src/plugins/nonebot_plugin_heweather/templates
=========================== logs ===========================
navigating to "file://src/plugins/nonebot_plugin_heweather/templates", waiting until "load"
============================================================
[36mATRI[0m | 03-03 18:09:31 | ERROR nonebot >> Error when running RunPostProcessors
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fe94766b040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fe94f7df130>
         │    └ <function MultiCommand.invoke at 0x7fe94766f0d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fe94f8b3d30>
           │               │       │       └ <function Command.invoke at 0x7fe94766baf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7fe94f8b3d30>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fe947eb8a60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7fe94f8b3d30>
           │   │      │    └ <function run at 0x7fe93e6b75e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7fe9478e88b0>
           └ <click.core.Context object at 0x7fe94f8b3d30>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7fe93e6a63a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7fe9407b0550>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7fe9407b00d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7fe93e4b4280>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7fe93e4b4670>
    └ <uvicorn.server.Server object at 0x7fe91d5f0e50>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fe93e4b4700>
           │       │   └ <uvicorn.server.Server object at 0x7fe91d5f0e50>
           │       └ <function run at 0x7fe943efe0d0>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fe91d5f9840>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 227, in _run_matcher
    await asyncio.gather(*coros)
          │       │       └ [<coroutine object _run_coro_with_catch at 0x7fe91c129740>]
          │       └ <function gather at 0x7fe941d22c10>
          └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 115, in _run_coro_with_catch
    return await coro
                 └ <coroutine object Dependent.__call__ at 0x7fe91c0345c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'exception': Error('net::ERR_INVALID_URL at file://src/plugins/nonebot_plugin_heweather/templates\n=========================...
                 │    └ <function _track_error at 0x7fe939ae6820>
                 └ <Dependent call=<function _track_error at 0x7fe939ae6820>, params=[ModelField(name='exception', type=Optional[Exception], req...
  File "/usr/local/python3/lib/python3.8/site-packages/ATRI/exceptions.py", line 115, in _track_error
    await bot.send_private_msg(user_id=superusers, message=msg)
          │                            │                   └ '呜——出错了...追踪: j5kCOS3i'
          │                            └ '1234567890'
          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/bot.py", line 208, in call_api
    return await super().call_api(api, **data)
                                  │      └ {'user_id': '1234567890', 'message': '呜——出错了...追踪: j5kCOS3i'}
                                  └ 'send_private_msg'
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 117, in call_api
    raise exception
          └ <ActionFailed data=None, echo={'seq': 4}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
                   │    │       │         │     │      └ {'user_id': '1234567890', 'message': '呜——出错了...追踪: j5kCOS3i'}
                   │    │       │         │     └ 'send_private_msg'
                   │    │       │         └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
                   │    │       └ <function Adapter._call_api at 0x7fe93e5d1b80>
                   │    └ <nonebot.adapters.onebot.v11.adapter.Adapter object at 0x7fe93e6c04c0>
                   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 107, in _call_api
    return _handle_api_result(
           └ <function _handle_api_result at 0x7fe93e65f310>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/utils.py", line 81, in _handle_api_result
    raise ActionFailed(**result)
          │              └ {'data': None, 'echo': {'seq': 4}, 'msg': 'SEND_MSG_API_ERROR', 'retcode': 100, 'status': 'failed', 'wording': '请参考 go-cqhttp...
          └ <class 'nonebot.adapters.onebot.v11.exception.ActionFailed'>

nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 4}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
[36mATRI[0m | 03-03 18:10:41 | ERROR nonebot >> Running matcher <Matcher from src.plugins.nonebot_plugin_heweather, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fe94766b040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fe94f7df130>
         │    └ <function MultiCommand.invoke at 0x7fe94766f0d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fe94f8b3d30>
           │               │       │       └ <function Command.invoke at 0x7fe94766baf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7fe94f8b3d30>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fe947eb8a60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7fe94f8b3d30>
           │   │      │    └ <function run at 0x7fe93e6b75e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7fe9478e88b0>
           └ <click.core.Context object at 0x7fe94f8b3d30>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7fe93e6a63a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7fe9407b0550>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7fe9407b00d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7fe93e4b4280>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7fe93e4b4670>
    └ <uvicorn.server.Server object at 0x7fe91d5f0e50>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fe93e4b4700>
           │       │   └ <uvicorn.server.Server object at 0x7fe91d5f0e50>
           │       └ <function run at 0x7fe943efe0d0>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fe91d5f9840>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0x7fe9407d2d30>: <Task finished name='Task-9532' coro=<_command() done, defined at /usr/local/python3/...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7fe9143af910>
          │            │        │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None}, '_matched': '/深圳天气', '_matched_groups': ('/深圳',), '_...
          │            │        │    └ GroupMessageEvent(time=1646302241, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │            │        └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
          │            └ <Matcher from src.plugins.nonebot_plugin_heweather, type=message, priority=1, temp=False>
          └ <function _run_matcher at 0x7fe93e5d1280>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0x7fe9407d2d30>: <Task finished name='Task-9532' coro=<_command() done, defined at /usr/local/python3/...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7fe9143af910>
          │       │   │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None}, '_matched': '/深圳天气', '_matched_groups': ('/深圳',), '_...
          │       │   │    └ GroupMessageEvent(time=1646302241, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
          │       └ <function Matcher.run at 0x7fe9407d2790>
          └ <Matcher from src.plugins.nonebot_plugin_heweather, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0x7fe9407d2d30>: <Task finished name='Task-9532' coro=<_command() done, defined at /usr/local/python3/...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7fe9143af910>
          │    │          │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None}, '_matched': '/深圳天气', '_matched_groups': ('/深圳',), '_...
          │    │          │    └ GroupMessageEvent(time=1646302241, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
          │    └ <function Matcher.simple_run at 0x7fe9407d2700>
          └ <Matcher from src.plugins.nonebot_plugin_heweather, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function _ at 0x7fe91d7769d0>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='eve...
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'bot': <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>, 'event': GroupMessageEvent(time=1646302241, self_id=5...
                 │    └ <function _ at 0x7fe91d7769d0>
                 └ <Dependent call=<function _ at 0x7fe91d7769d0>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='eve...

  File "./src/plugins/nonebot_plugin_heweather/__init__.py", line 35, in _
    img = await render(w_data)
                │      └ <src.plugins.nonebot_plugin_heweather.weather_data.Weather object at 0x7fe91c0af910>
                └ <function render at 0x7fe91d783550>

  File "./src/plugins/nonebot_plugin_heweather/render_pic.py", line 11, in render
    return await template_to_pic(
                 └ <function template_to_pic at 0x7fe920d753a0>

  File "/usr/local/python3/lib/python3.8/site-packages/nonebot_plugin_htmlrender/date_source.py", line 194, in template_to_pic
    return await html_to_pic(
                 └ <function html_to_pic at 0x7fe920d75310>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot_plugin_htmlrender/date_source.py", line 159, in html_to_pic
    await page.goto(template_path)
          │    │    └ 'file://src/plugins/nonebot_plugin_heweather/templates'
          │    └ <function Page.goto at 0x7fe921070e50>
          └ <Page url='about:blank'>
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 7516, in goto
    await self._async(
          │    └ <function AsyncBase._async at 0x7fe9210b3670>
          └ <Page url='about:blank'>
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_page.py", line 487, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
                 │    │           │      └ <function locals_to_params at 0x7fe9213fd700>
                 │    │           └ <function Frame.goto at 0x7fe92110a550>
                 │    └ <Frame name= url='about:blank'>
                 └ <Page url='about:blank'>
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_frame.py", line 122, in goto
    await self._channel.send("goto", locals_to_params(locals()))
          │    │        │            └ <function locals_to_params at 0x7fe9213fd700>
          │    │        └ <function Channel.send at 0x7fe9213dfb80>
          │    └ <playwright._impl._connection.Channel object at 0x7fe91c1105e0>
          └ <Frame name= url='about:blank'>
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
                 │    │          │       └ {'url': 'file://src/plugins/nonebot_plugin_heweather/templates'}
                 │    │          └ 'goto'
                 │    └ <function Channel.inner_send at 0x7fe9213d7820>
                 └ <playwright._impl._connection.Channel object at 0x7fe91c1105e0>
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
                       └ {<Future finished exception=Error('net::ERR_INVALID_URL at file://src/plugins/nonebot_plugin_heweather/templates\n===========...

playwright._impl._api_types.Error: net::ERR_INVALID_URL at file://src/plugins/nonebot_plugin_heweather/templates
=========================== logs ===========================
navigating to "file://src/plugins/nonebot_plugin_heweather/templates", waiting until "load"
============================================================
[36mATRI[0m | 03-03 18:10:42 | ERROR nonebot >> Error when running RunPostProcessors
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fe94766b040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fe94f7df130>
         │    └ <function MultiCommand.invoke at 0x7fe94766f0d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fe94f8b3d30>
           │               │       │       └ <function Command.invoke at 0x7fe94766baf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7fe94f8b3d30>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fe947eb8a60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7fe94f8b3d30>
           │   │      │    └ <function run at 0x7fe93e6b75e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7fe9478e88b0>
           └ <click.core.Context object at 0x7fe94f8b3d30>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7fe93e6a63a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7fe9407b0550>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7fe9407b00d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7fe93e4b4280>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7fe93e4b4670>
    └ <uvicorn.server.Server object at 0x7fe91d5f0e50>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fe93e4b4700>
           │       │   └ <uvicorn.server.Server object at 0x7fe91d5f0e50>
           │       └ <function run at 0x7fe943efe0d0>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fe91d5f9840>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 227, in _run_matcher
    await asyncio.gather(*coros)
          │       │       └ [<coroutine object _run_coro_with_catch at 0x7fe91436fac0>]
          │       └ <function gather at 0x7fe941d22c10>
          └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 115, in _run_coro_with_catch
    return await coro
                 └ <coroutine object Dependent.__call__ at 0x7fe91c99c840>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'exception': Error('net::ERR_INVALID_URL at file://src/plugins/nonebot_plugin_heweather/templates\n=========================...
                 │    └ <function _track_error at 0x7fe939ae6820>
                 └ <Dependent call=<function _track_error at 0x7fe939ae6820>, params=[ModelField(name='exception', type=Optional[Exception], req...
  File "/usr/local/python3/lib/python3.8/site-packages/ATRI/exceptions.py", line 115, in _track_error
    await bot.send_private_msg(user_id=superusers, message=msg)
          │                            │                   └ '呜——出错了...追踪: XpQSHWC4'
          │                            └ '1234567890'
          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/bot.py", line 208, in call_api
    return await super().call_api(api, **data)
                                  │      └ {'user_id': '1234567890', 'message': '呜——出错了...追踪: XpQSHWC4'}
                                  └ 'send_private_msg'
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 117, in call_api
    raise exception
          └ <ActionFailed data=None, echo={'seq': 5}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
                   │    │       │         │     │      └ {'user_id': '1234567890', 'message': '呜——出错了...追踪: XpQSHWC4'}
                   │    │       │         │     └ 'send_private_msg'
                   │    │       │         └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
                   │    │       └ <function Adapter._call_api at 0x7fe93e5d1b80>
                   │    └ <nonebot.adapters.onebot.v11.adapter.Adapter object at 0x7fe93e6c04c0>
                   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 107, in _call_api
    return _handle_api_result(
           └ <function _handle_api_result at 0x7fe93e65f310>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/utils.py", line 81, in _handle_api_result
    raise ActionFailed(**result)
          │              └ {'data': None, 'echo': {'seq': 5}, 'msg': 'SEND_MSG_API_ERROR', 'retcode': 100, 'status': 'failed', 'wording': '请参考 go-cqhttp...
          └ <class 'nonebot.adapters.onebot.v11.exception.ActionFailed'>

nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 5}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
[36mATRI[0m | 03-03 18:16:27 | ERROR nonebot >> Running matcher <Matcher from src.plugins.saying, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fe94766b040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fe94f7df130>
         │    └ <function MultiCommand.invoke at 0x7fe94766f0d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fe94f8b3d30>
           │               │       │       └ <function Command.invoke at 0x7fe94766baf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7fe94f8b3d30>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fe947eb8a60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7fe94f8b3d30>
           │   │      │    └ <function run at 0x7fe93e6b75e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7fe9478e88b0>
           └ <click.core.Context object at 0x7fe94f8b3d30>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7fe93e6a63a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7fe9407b0550>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7fe9407b00d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7fe93e4b4280>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7fe93e4b4670>
    └ <uvicorn.server.Server object at 0x7fe91d5f0e50>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fe93e4b4700>
           │       │   └ <uvicorn.server.Server object at 0x7fe91d5f0e50>
           │       └ <function run at 0x7fe943efe0d0>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fe91d5f9840>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0x7fe9407d2d30>: <Task finished name='Task-24176' coro=<_command() done, defined at /usr/local/python3...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7fe8f80a3160>
          │            │        │    │      └ {'_prefix': {'command': ('saying',), 'raw_command': '/saying', 'command_arg': []}}
          │            │        │    └ GroupMessageEvent(time=1646302582, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │            │        └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
          │            └ <Matcher from src.plugins.saying, type=message, priority=1, temp=False>
          └ <function _run_matcher at 0x7fe93e5d1280>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0x7fe9407d2d30>: <Task finished name='Task-24176' coro=<_command() done, defined at /usr/local/python3...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7fe8f80a3160>
          │       │   │    │      └ {'_prefix': {'command': ('saying',), 'raw_command': '/saying', 'command_arg': []}}
          │       │   │    └ GroupMessageEvent(time=1646302582, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
          │       └ <function Matcher.run at 0x7fe9407d2790>
          └ <Matcher from src.plugins.saying, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0x7fe9407d2d30>: <Task finished name='Task-24176' coro=<_command() done, defined at /usr/local/python3...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7fe8f80a3160>
          │    │          │    │      └ {'_prefix': {'command': ('saying',), 'raw_command': '/saying', 'command_arg': []}}
          │    │          │    └ GroupMessageEvent(time=1646302582, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
          │    └ <function Matcher.simple_run at 0x7fe9407d2700>
          └ <Matcher from src.plugins.saying, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function handle at 0x7fe91f79ef70>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name...
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'bot': <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>, 'event': GroupMessageEvent(time=1646302582, self_id=5...
                 │    └ <function handle at 0x7fe91f79ef70>
                 └ <Dependent call=<function handle at 0x7fe91f79ef70>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name...

  File "./src/plugins/saying/__init__.py", line 44, in handle
    await saying.send(result)
          │      │    └ '【一言】小舟从此逝，江海寄余生。\n来源：临江仙·夜饮东坡醒复醉\n作者：a632079\n类型：诗词'
          │      └ <classmethod object at 0x7fe9407ca6d0>
          └ <Matcher from src.plugins.saying, type=message, priority=1, temp=False>

  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 449, in send
    return await bot.send(event=event, message=_message, **kwargs)
                 │   │          │              │           └ {}
                 │   │          │              └ '【一言】小舟从此逝，江海寄余生。\n来源：临江仙·夜饮东坡醒复醉\n作者：a632079\n类型：诗词'
                 │   │          └ GroupMessageEvent(time=1646302582, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
                 │   └ <function Bot.send at 0x7fe93e5d1790>
                 └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/bot.py", line 247, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
                 │    │                      │     │      │          └ {}
                 │    │                      │     │      └ '【一言】小舟从此逝，江海寄余生。\n来源：临江仙·夜饮东坡醒复醉\n作者：a632079\n类型：诗词'
                 │    │                      │     └ GroupMessageEvent(time=1646302582, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
                 │    │                      └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
                 │    └ <attribute '__class__' of 'object' objects>
                 └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/bot.py", line 175, in send
    return await bot.send_msg(**params)
                 │              └ {'user_id': 2560359315, 'group_id': 277620613, 'message_type': 'group', 'message': [MessageSegment(type='text', data={'text':...
                 └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/bot.py", line 208, in call_api
    return await super().call_api(api, **data)
                                  │      └ {'user_id': 2560359315, 'group_id': 277620613, 'message_type': 'group', 'message': [MessageSegment(type='text', data={'text':...
                                  └ 'send_msg'
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 117, in call_api
    raise exception
          └ <ActionFailed data=None, echo={'seq': 13}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
                   │    │       │         │     │      └ {'user_id': 2560359315, 'group_id': 277620613, 'message_type': 'group', 'message': [MessageSegment(type='text', data={'text':...
                   │    │       │         │     └ 'send_msg'
                   │    │       │         └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
                   │    │       └ <function Adapter._call_api at 0x7fe93e5d1b80>
                   │    └ <nonebot.adapters.onebot.v11.adapter.Adapter object at 0x7fe93e6c04c0>
                   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 107, in _call_api
    return _handle_api_result(
           └ <function _handle_api_result at 0x7fe93e65f310>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/utils.py", line 81, in _handle_api_result
    raise ActionFailed(**result)
          │              └ {'data': None, 'echo': {'seq': 13}, 'msg': 'SEND_MSG_API_ERROR', 'retcode': 100, 'status': 'failed', 'wording': '请参考 go-cqhtt...
          └ <class 'nonebot.adapters.onebot.v11.exception.ActionFailed'>

nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 13}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
[36mATRI[0m | 03-03 18:16:28 | ERROR nonebot >> Error when running RunPostProcessors
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fe94766b040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fe94f7df130>
         │    └ <function MultiCommand.invoke at 0x7fe94766f0d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fe94f8b3d30>
           │               │       │       └ <function Command.invoke at 0x7fe94766baf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7fe94f8b3d30>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fe947eb8a60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7fe94f8b3d30>
           │   │      │    └ <function run at 0x7fe93e6b75e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7fe9478e88b0>
           └ <click.core.Context object at 0x7fe94f8b3d30>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7fe93e6a63a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7fe9407b0550>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7fe9407b00d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7fe93e4b4280>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7fe93e4b4670>
    └ <uvicorn.server.Server object at 0x7fe91d5f0e50>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fe93e4b4700>
           │       │   └ <uvicorn.server.Server object at 0x7fe91d5f0e50>
           │       └ <function run at 0x7fe943efe0d0>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fe91d5f9840>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 227, in _run_matcher
    await asyncio.gather(*coros)
          │       │       └ [<coroutine object _run_coro_with_catch at 0x7fe91c10ef40>]
          │       └ <function gather at 0x7fe941d22c10>
          └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 115, in _run_coro_with_catch
    return await coro
                 └ <coroutine object Dependent.__call__ at 0x7fe91c97c440>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'exception': <ActionFailed data=None, echo={'seq': 13}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-c...
                 │    └ <function _track_error at 0x7fe939ae6820>
                 └ <Dependent call=<function _track_error at 0x7fe939ae6820>, params=[ModelField(name='exception', type=Optional[Exception], req...
  File "/usr/local/python3/lib/python3.8/site-packages/ATRI/exceptions.py", line 115, in _track_error
    await bot.send_private_msg(user_id=superusers, message=msg)
          │                            │                   └ '呜——出错了...追踪: QBLyrvq8'
          │                            └ '1234567890'
          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/bot.py", line 208, in call_api
    return await super().call_api(api, **data)
                                  │      └ {'user_id': '1234567890', 'message': '呜——出错了...追踪: QBLyrvq8'}
                                  └ 'send_private_msg'
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 117, in call_api
    raise exception
          └ <ActionFailed data=None, echo={'seq': 14}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
                   │    │       │         │     │      └ {'user_id': '1234567890', 'message': '呜——出错了...追踪: QBLyrvq8'}
                   │    │       │         │     └ 'send_private_msg'
                   │    │       │         └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
                   │    │       └ <function Adapter._call_api at 0x7fe93e5d1b80>
                   │    └ <nonebot.adapters.onebot.v11.adapter.Adapter object at 0x7fe93e6c04c0>
                   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 107, in _call_api
    return _handle_api_result(
           └ <function _handle_api_result at 0x7fe93e65f310>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/utils.py", line 81, in _handle_api_result
    raise ActionFailed(**result)
          │              └ {'data': None, 'echo': {'seq': 14}, 'msg': 'SEND_MSG_API_ERROR', 'retcode': 100, 'status': 'failed', 'wording': '请参考 go-cqhtt...
          └ <class 'nonebot.adapters.onebot.v11.exception.ActionFailed'>

nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 14}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
[36mATRI[0m | 03-03 19:43:40 | ERROR nonebot >> Running matcher <Matcher from src.plugins.saying, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fe94766b040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fe94f7df130>
         │    └ <function MultiCommand.invoke at 0x7fe94766f0d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fe94f8b3d30>
           │               │       │       └ <function Command.invoke at 0x7fe94766baf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7fe94f8b3d30>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fe947eb8a60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7fe94f8b3d30>
           │   │      │    └ <function run at 0x7fe93e6b75e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7fe9478e88b0>
           └ <click.core.Context object at 0x7fe94f8b3d30>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7fe93e6a63a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7fe9407b0550>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7fe9407b00d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7fe93e4b4280>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7fe93e4b4670>
    └ <uvicorn.server.Server object at 0x7fe91d5f0e50>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fe93e4b4700>
           │       │   └ <uvicorn.server.Server object at 0x7fe91d5f0e50>
           │       └ <function run at 0x7fe943efe0d0>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fe91d5f9840>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0x7fe9407d2d30>: <Task finished name='Task-266187' coro=<_command() done, defined at /usr/local/python...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7fe8f80743a0>
          │            │        │    │      └ {'_prefix': {'command': ('saying',), 'raw_command': '/saying', 'command_arg': []}}
          │            │        │    └ GroupMessageEvent(time=1646307803, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │            │        └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
          │            └ <Matcher from src.plugins.saying, type=message, priority=1, temp=False>
          └ <function _run_matcher at 0x7fe93e5d1280>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0x7fe9407d2d30>: <Task finished name='Task-266187' coro=<_command() done, defined at /usr/local/python...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7fe8f80743a0>
          │       │   │    │      └ {'_prefix': {'command': ('saying',), 'raw_command': '/saying', 'command_arg': []}}
          │       │   │    └ GroupMessageEvent(time=1646307803, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
          │       └ <function Matcher.run at 0x7fe9407d2790>
          └ <Matcher from src.plugins.saying, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0x7fe9407d2d30>: <Task finished name='Task-266187' coro=<_command() done, defined at /usr/local/python...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7fe8f80743a0>
          │    │          │    │      └ {'_prefix': {'command': ('saying',), 'raw_command': '/saying', 'command_arg': []}}
          │    │          │    └ GroupMessageEvent(time=1646307803, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
          │    └ <function Matcher.simple_run at 0x7fe9407d2700>
          └ <Matcher from src.plugins.saying, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function handle at 0x7fe91f79ef70>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name...
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'bot': <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>, 'event': GroupMessageEvent(time=1646307803, self_id=5...
                 │    └ <function handle at 0x7fe91f79ef70>
                 └ <Dependent call=<function handle at 0x7fe91f79ef70>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name...

  File "./src/plugins/saying/__init__.py", line 44, in handle
    await saying.send(result)
          │      │    └ '【一言】你是否会等待着我？我会变得更加完美！\n来源：Aqours\n作者：BillZhou233\n类型：动画'
          │      └ <classmethod object at 0x7fe9407ca6d0>
          └ <Matcher from src.plugins.saying, type=message, priority=1, temp=False>

  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 449, in send
    return await bot.send(event=event, message=_message, **kwargs)
                 │   │          │              │           └ {}
                 │   │          │              └ '【一言】你是否会等待着我？我会变得更加完美！\n来源：Aqours\n作者：BillZhou233\n类型：动画'
                 │   │          └ GroupMessageEvent(time=1646307803, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
                 │   └ <function Bot.send at 0x7fe93e5d1790>
                 └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/bot.py", line 247, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
                 │    │                      │     │      │          └ {}
                 │    │                      │     │      └ '【一言】你是否会等待着我？我会变得更加完美！\n来源：Aqours\n作者：BillZhou233\n类型：动画'
                 │    │                      │     └ GroupMessageEvent(time=1646307803, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
                 │    │                      └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
                 │    └ <attribute '__class__' of 'object' objects>
                 └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/bot.py", line 175, in send
    return await bot.send_msg(**params)
                 │              └ {'user_id': 2560359315, 'group_id': 277620613, 'message_type': 'group', 'message': [MessageSegment(type='text', data={'text':...
                 └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/bot.py", line 208, in call_api
    return await super().call_api(api, **data)
                                  │      └ {'user_id': 2560359315, 'group_id': 277620613, 'message_type': 'group', 'message': [MessageSegment(type='text', data={'text':...
                                  └ 'send_msg'
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 117, in call_api
    raise exception
          └ <ActionFailed data=None, echo={'seq': 224}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
                   │    │       │         │     │      └ {'user_id': 2560359315, 'group_id': 277620613, 'message_type': 'group', 'message': [MessageSegment(type='text', data={'text':...
                   │    │       │         │     └ 'send_msg'
                   │    │       │         └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
                   │    │       └ <function Adapter._call_api at 0x7fe93e5d1b80>
                   │    └ <nonebot.adapters.onebot.v11.adapter.Adapter object at 0x7fe93e6c04c0>
                   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 107, in _call_api
    return _handle_api_result(
           └ <function _handle_api_result at 0x7fe93e65f310>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/utils.py", line 81, in _handle_api_result
    raise ActionFailed(**result)
          │              └ {'data': None, 'echo': {'seq': 224}, 'msg': 'SEND_MSG_API_ERROR', 'retcode': 100, 'status': 'failed', 'wording': '请参考 go-cqht...
          └ <class 'nonebot.adapters.onebot.v11.exception.ActionFailed'>

nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 224}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
[36mATRI[0m | 03-03 19:43:41 | ERROR nonebot >> Error when running RunPostProcessors
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fe94766b040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fe94f7df130>
         │    └ <function MultiCommand.invoke at 0x7fe94766f0d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fe94f8b3d30>
           │               │       │       └ <function Command.invoke at 0x7fe94766baf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7fe94f8b3d30>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fe947eb8a60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7fe94f8b3d30>
           │   │      │    └ <function run at 0x7fe93e6b75e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7fe9478e88b0>
           └ <click.core.Context object at 0x7fe94f8b3d30>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7fe93e6a63a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7fe9407b0550>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7fe9407b00d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7fe93e4b4280>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7fe93e4b4670>
    └ <uvicorn.server.Server object at 0x7fe91d5f0e50>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fe93e4b4700>
           │       │   └ <uvicorn.server.Server object at 0x7fe91d5f0e50>
           │       └ <function run at 0x7fe943efe0d0>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fe91d5f9840>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 227, in _run_matcher
    await asyncio.gather(*coros)
          │       │       └ [<coroutine object _run_coro_with_catch at 0x7fe91c10ce40>]
          │       └ <function gather at 0x7fe941d22c10>
          └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 115, in _run_coro_with_catch
    return await coro
                 └ <coroutine object Dependent.__call__ at 0x7fe91439d0c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'exception': <ActionFailed data=None, echo={'seq': 224}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-...
                 │    └ <function _track_error at 0x7fe939ae6820>
                 └ <Dependent call=<function _track_error at 0x7fe939ae6820>, params=[ModelField(name='exception', type=Optional[Exception], req...
  File "/usr/local/python3/lib/python3.8/site-packages/ATRI/exceptions.py", line 115, in _track_error
    await bot.send_private_msg(user_id=superusers, message=msg)
          │                            │                   └ '呜——出错了...追踪: b4fK3M8h'
          │                            └ '1234567890'
          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/bot.py", line 208, in call_api
    return await super().call_api(api, **data)
                                  │      └ {'user_id': '1234567890', 'message': '呜——出错了...追踪: b4fK3M8h'}
                                  └ 'send_private_msg'
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 117, in call_api
    raise exception
          └ <ActionFailed data=None, echo={'seq': 226}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
                   │    │       │         │     │      └ {'user_id': '1234567890', 'message': '呜——出错了...追踪: b4fK3M8h'}
                   │    │       │         │     └ 'send_private_msg'
                   │    │       │         └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
                   │    │       └ <function Adapter._call_api at 0x7fe93e5d1b80>
                   │    └ <nonebot.adapters.onebot.v11.adapter.Adapter object at 0x7fe93e6c04c0>
                   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fe91d5fd4c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 107, in _call_api
    return _handle_api_result(
           └ <function _handle_api_result at 0x7fe93e65f310>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/utils.py", line 81, in _handle_api_result
    raise ActionFailed(**result)
          │              └ {'data': None, 'echo': {'seq': 226}, 'msg': 'SEND_MSG_API_ERROR', 'retcode': 100, 'status': 'failed', 'wording': '请参考 go-cqht...
          └ <class 'nonebot.adapters.onebot.v11.exception.ActionFailed'>

nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 226}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
