[36mATRI[0m | 03-02 21:06:29 | ERROR plugin.manager >> Failed to import "whitenight_from_feiyucans_space"
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f741ff2e040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f74280a2130>
         │    └ <function MultiCommand.invoke at 0x7f741ff320d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f74280a7ca0>
           │               │       │       └ <function Command.invoke at 0x7f741ff2eaf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7f74280a7ca0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f742077aa60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7f74280a7ca0>
           │   │      │    └ <function run at 0x7f7416f7a5e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7f74201ab8b0>
           └ <click.core.Context object at 0x7f74280a7ca0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7f7416f6a3a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
             │         │             └ 'bot'
             │         └ <function import_module at 0x7f74280e28b0>
             └ <module 'importlib' from '/usr/local/python3/lib/python3.8/importlib/__init__.py'>
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'bot'
           │          └ <function _gcd_import at 0x7f7428211430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./bot.py", line 29, in <module>
    nonebot.load_plugins("src/plugins")
    │       └ <function load_plugins at 0x7f741ddaa3a0>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>

  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/load.py", line 39, in load_plugins
    return manager.load_all_plugins()
           │       └ <function PluginManager.load_all_plugins at 0x7f741dd9cee0>
           └ <nonebot.plugin.manager.PluginManager object at 0x7f741675f8e0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 128, in load_all_plugins
    return set(
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
                  │    │           │         │       │    └ <function PluginManager.list_plugins at 0x7f741dd9cdc0>
                  │    │           │         │       └ <nonebot.plugin.manager.PluginManager object at 0x7f741675f8e0>
                  │    │           │         └ 'whitenight_from_feiyucans_space'
                  │    │           └ 'whitenight_from_feiyucans_space'
                  │    └ <function PluginManager.load_plugin at 0x7f741dd9ce50>
                  └ <nonebot.plugin.manager.PluginManager object at 0x7f741675f8e0>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 106, in load_plugin
    module = importlib.import_module(
             │         └ <function import_module at 0x7f74280e28b0>
             └ <module 'importlib' from '/usr/local/python3/lib/python3.8/importlib/__init__.py'>
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'src.plugins.whitenight_from_feiyucans_space'
           │          └ <function _gcd_import at 0x7f7428211430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 194, in exec_module
    super().exec_module(module)
                        └ <module 'src.plugins.whitenight_from_feiyucans_space' from './src/plugins/whitenight_from_feiyucans_space/__init__.py'>
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./src/plugins/whitenight_from_feiyucans_space/__init__.py", line 78, in <module>
    scheduler.add_job(whitenight, "cron", hour=22, minute=30, id=146487)
    │         │       └ <function whitenight at 0x7f73f7592d30>
    │         └ <function BaseScheduler.add_job at 0x7f740defb310>
    └ <apscheduler.schedulers.asyncio.AsyncIOScheduler object at 0x7f740df41730>

  File "/usr/local/python3/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 439, in add_job
    job = Job(self, **job_kwargs)
          │   │       └ {'trigger': <CronTrigger (hour='22', minute='30', timezone='Asia/Shanghai')>, 'executor': 'default', 'func': <function whiten...
          │   └ <apscheduler.schedulers.asyncio.AsyncIOScheduler object at 0x7f740df41730>
          └ <class 'apscheduler.job.Job'>
  File "/usr/local/python3/lib/python3.8/site-packages/apscheduler/job.py", line 49, in __init__
    self._modify(id=id or uuid4().hex, **kwargs)
    │    │          │     │              └ {'trigger': <CronTrigger (hour='22', minute='30', timezone='Asia/Shanghai')>, 'executor': 'default', 'func': <function whiten...
    │    │          │     └ <function uuid4 at 0x7f741d54bf70>
    │    │          └ 146487
    │    └ <function Job._modify at 0x7f740ded59d0>
    └ <unprintable Job object>
  File "/usr/local/python3/lib/python3.8/site-packages/apscheduler/job.py", line 150, in _modify
    raise TypeError("id must be a nonempty string")

TypeError: id must be a nonempty string
[36mATRI[0m | 03-02 21:06:30 | ERROR plugin.manager >> Failed to import "nonebot_plugin_statistical"
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f741ff2e040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f74280a2130>
         │    └ <function MultiCommand.invoke at 0x7f741ff320d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f74280a7ca0>
           │               │       │       └ <function Command.invoke at 0x7f741ff2eaf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7f74280a7ca0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f742077aa60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7f74280a7ca0>
           │   │      │    └ <function run at 0x7f7416f7a5e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7f74201ab8b0>
           └ <click.core.Context object at 0x7f74280a7ca0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7f7416f6a3a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
             │         │             └ 'bot'
             │         └ <function import_module at 0x7f74280e28b0>
             └ <module 'importlib' from '/usr/local/python3/lib/python3.8/importlib/__init__.py'>
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'bot'
           │          └ <function _gcd_import at 0x7f7428211430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./bot.py", line 29, in <module>
    nonebot.load_plugins("src/plugins")
    │       └ <function load_plugins at 0x7f741ddaa3a0>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>

  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/load.py", line 39, in load_plugins
    return manager.load_all_plugins()
           │       └ <function PluginManager.load_all_plugins at 0x7f741dd9cee0>
           └ <nonebot.plugin.manager.PluginManager object at 0x7f741675f8e0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 128, in load_all_plugins
    return set(
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
                  │    │           │         │       │    └ <function PluginManager.list_plugins at 0x7f741dd9cdc0>
                  │    │           │         │       └ <nonebot.plugin.manager.PluginManager object at 0x7f741675f8e0>
                  │    │           │         └ 'nonebot_plugin_statistical'
                  │    │           └ 'nonebot_plugin_statistical'
                  │    └ <function PluginManager.load_plugin at 0x7f741dd9ce50>
                  └ <nonebot.plugin.manager.PluginManager object at 0x7f741675f8e0>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 106, in load_plugin
    module = importlib.import_module(
             │         └ <function import_module at 0x7f74280e28b0>
             └ <module 'importlib' from '/usr/local/python3/lib/python3.8/importlib/__init__.py'>
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'src.plugins.nonebot_plugin_statistical'
           │          └ <function _gcd_import at 0x7f7428211430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 194, in exec_module
    super().exec_module(module)
                        └ <module 'src.plugins.nonebot_plugin_statistical' from './src/plugins/nonebot_plugin_statistical/__init__.py'>
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./src/plugins/nonebot_plugin_statistical/__init__.py", line 1, in <module>
    from .statistical_hook import *

  File "./src/plugins/nonebot_plugin_statistical/statistical_hook.py", line 7, in <module>
    from .config import save_data, get_prefix_group_count_dict, get_prefix_user_count_dict, \

  File "./src/plugins/nonebot_plugin_statistical/config.py", line 149, in <module>
    plugin2cmd: dict = json.load(f)
                       │    │    └ <_io.TextIOWrapper name='/root/Projects/Kori-Bot/Kori-bot/data/statistical/plugin2cmd.json' mode='r' encoding='utf8'>
                       │    └ <built-in function load>
                       └ <module 'ujson' from '/usr/local/python3/lib/python3.8/site-packages/ujson.cpython-38-x86_64-linux-gnu.so'>

ValueError: Expected object or value
[36mATRI[0m | 03-02 21:28:43 | ERROR nonebot >> Running matcher <Matcher from src.plugins.nonebot_plugin_status, type=notice, priority=10, temp=False> failed.
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f741ff2e040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f74280a2130>
         │    └ <function MultiCommand.invoke at 0x7f741ff320d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f74280a7ca0>
           │               │       │       └ <function Command.invoke at 0x7f741ff2eaf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7f74280a7ca0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f742077aa60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7f74280a7ca0>
           │   │      │    └ <function run at 0x7f7416f7a5e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7f74201ab8b0>
           └ <click.core.Context object at 0x7f74280a7ca0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7f7416f6a3a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7f7419073550>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7f74190730d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7f7416d76280>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7f7416d76670>
    └ <uvicorn.server.Server object at 0x7f73f5c125e0>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f7416d76700>
           │       │   └ <uvicorn.server.Server object at 0x7f73f5c125e0>
           │       └ <function run at 0x7f741c7c10d0>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f73f5c52740>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {}
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7f73d8b90d30>
          │            │        │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None}}
          │            │        │    └ PokeNotifyEvent(time=1646227722, self_id=507346814, post_type='notice', notice_type='notify', sub_type='poke', user_id=871389...
          │            │        └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f73f4fc9d30>
          │            └ <Matcher from src.plugins.nonebot_plugin_status, type=notice, priority=10, temp=False>
          └ <function _run_matcher at 0x7f7416e94280>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {}
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7f73d8b90d30>
          │       │   │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None}}
          │       │   │    └ PokeNotifyEvent(time=1646227722, self_id=507346814, post_type='notice', notice_type='notify', sub_type='poke', user_id=871389...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f73f4fc9d30>
          │       └ <function Matcher.run at 0x7f7419095790>
          └ <Matcher from src.plugins.nonebot_plugin_status, type=notice, priority=10, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {}
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7f73d8b90d30>
          │    │          │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None}}
          │    │          │    └ PokeNotifyEvent(time=1646227722, self_id=507346814, post_type='notice', notice_type='notify', sub_type='poke', user_id=871389...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f73f4fc9d30>
          │    └ <function Matcher.simple_run at 0x7f7419095700>
          └ <Matcher from src.plugins.nonebot_plugin_status, type=notice, priority=10, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function server_status at 0x7f73f745edc0>, params=[ModelField(name='matcher', type=Matcher, required=True)],...
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'matcher': <Matcher from src.plugins.nonebot_plugin_status, type=notice, priority=10, temp=False>}
                 │    └ <function server_status at 0x7f73f745edc0>
                 └ <Dependent call=<function server_status at 0x7f73f745edc0>, params=[ModelField(name='matcher', type=Matcher, required=True)],...

  File "./src/plugins/nonebot_plugin_status/__init__.py", line 64, in server_status
    pic = await md_to_pic(md=data)
                │            └ ['CPU:', '  core1: 07%', '  core2: 11%', 'Memory: 75%', 'Disk:', '  /: 41%', '  /var/lib/docker/containers: 41%', '  /var/lib...
                └ <function md_to_pic at 0x7f73f745e9d0>

  File "./src/plugins/nonebot_plugin_status/data_source.py", line 75, in md_to_pic
    md = markdown.markdown(
         │        └ <function markdown at 0x7f74100b1160>
         └ <module 'markdown' from '/usr/local/python3/lib/python3.8/site-packages/markdown/__init__.py'>

  File "/usr/local/python3/lib/python3.8/site-packages/markdown/core.py", line 387, in markdown
    return md.convert(text)
           │  │       └ ['CPU:', '  core1: 07%', '  core2: 11%', 'Memory: 75%', 'Disk:', '  /: 41%', '  /var/lib/docker/containers: 41%', '  /var/lib...
           │  └ <function Markdown.convert at 0x7f740fd94790>
           └ <markdown.core.Markdown object at 0x7f73d8bb7460>
  File "/usr/local/python3/lib/python3.8/site-packages/markdown/core.py", line 248, in convert
    if not source.strip():
           └ ['CPU:', '  core1: 07%', '  core2: 11%', 'Memory: 75%', 'Disk:', '  /: 41%', '  /var/lib/docker/containers: 41%', '  /var/lib...

AttributeError: 'list' object has no attribute 'strip'
[36mATRI[0m | 03-02 21:28:44 | ERROR nonebot >> Error when running RunPostProcessors
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f741ff2e040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f74280a2130>
         │    └ <function MultiCommand.invoke at 0x7f741ff320d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f74280a7ca0>
           │               │       │       └ <function Command.invoke at 0x7f741ff2eaf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7f74280a7ca0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f742077aa60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7f74280a7ca0>
           │   │      │    └ <function run at 0x7f7416f7a5e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7f74201ab8b0>
           └ <click.core.Context object at 0x7f74280a7ca0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7f7416f6a3a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7f7419073550>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7f74190730d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7f7416d76280>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7f7416d76670>
    └ <uvicorn.server.Server object at 0x7f73f5c125e0>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f7416d76700>
           │       │   └ <uvicorn.server.Server object at 0x7f73f5c125e0>
           │       └ <function run at 0x7f741c7c10d0>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f73f5c52740>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 227, in _run_matcher
    await asyncio.gather(*coros)
          │       │       └ [<coroutine object _run_coro_with_catch at 0x7f73f4705f40>]
          │       └ <function gather at 0x7f741a5e5c10>
          └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 115, in _run_coro_with_catch
    return await coro
                 └ <coroutine object Dependent.__call__ at 0x7f73d8bb68c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'exception': AttributeError("'list' object has no attribute 'strip'"), 'bot': <nonebot.adapters.onebot.v11.bot.Bot object at...
                 │    └ <function _track_error at 0x7f73f75e04c0>
                 └ <Dependent call=<function _track_error at 0x7f73f75e04c0>, params=[ModelField(name='exception', type=Optional[Exception], req...
  File "/usr/local/python3/lib/python3.8/site-packages/ATRI/exceptions.py", line 115, in _track_error
    await bot.send_private_msg(user_id=superusers, message=msg)
          │                            │                   └ '呜——出错了...追踪: qw1doIpL'
          │                            └ '1234567890'
          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f73f4fc9d30>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/bot.py", line 208, in call_api
    return await super().call_api(api, **data)
                                  │      └ {'user_id': '1234567890', 'message': '呜——出错了...追踪: qw1doIpL'}
                                  └ 'send_private_msg'
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 117, in call_api
    raise exception
          └ <ActionFailed data=None, echo={'seq': 31}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
                   │    │       │         │     │      └ {'user_id': '1234567890', 'message': '呜——出错了...追踪: qw1doIpL'}
                   │    │       │         │     └ 'send_private_msg'
                   │    │       │         └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f73f4fc9d30>
                   │    │       └ <function Adapter._call_api at 0x7f7416e94b80>
                   │    └ <nonebot.adapters.onebot.v11.adapter.Adapter object at 0x7f7416f81820>
                   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f73f4fc9d30>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 107, in _call_api
    return _handle_api_result(
           └ <function _handle_api_result at 0x7f7416f22310>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/utils.py", line 81, in _handle_api_result
    raise ActionFailed(**result)
          │              └ {'data': None, 'echo': {'seq': 31}, 'msg': 'SEND_MSG_API_ERROR', 'retcode': 100, 'status': 'failed', 'wording': '请参考 go-cqhtt...
          └ <class 'nonebot.adapters.onebot.v11.exception.ActionFailed'>

nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 31}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
[36mATRI[0m | 03-02 22:13:09 | ERROR nonebot >> Running matcher <Matcher from src.plugins.nonebot_plugin_heweather, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f741ff2e040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f74280a2130>
         │    └ <function MultiCommand.invoke at 0x7f741ff320d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f74280a7ca0>
           │               │       │       └ <function Command.invoke at 0x7f741ff2eaf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7f74280a7ca0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f742077aa60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7f74280a7ca0>
           │   │      │    └ <function run at 0x7f7416f7a5e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7f74201ab8b0>
           └ <click.core.Context object at 0x7f74280a7ca0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7f7416f6a3a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7f7419073550>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7f74190730d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7f7416d76280>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7f7416d76670>
    └ <uvicorn.server.Server object at 0x7f73f5c125e0>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f7416d76700>
           │       │   └ <uvicorn.server.Server object at 0x7f73f5c125e0>
           │       └ <function run at 0x7f741c7c10d0>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f73f5c52740>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0x7f7419095d30>: <Task finished name='Task-197340' coro=<_command() done, defined at /usr/local/python...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7f73d86dc610>
          │            │        │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None}, '_matched': '深圳天气', '_matched_groups': ('深圳',), '_ma...
          │            │        │    └ GroupMessageEvent(time=1646230388, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │            │        └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f73f4fc9d30>
          │            └ <Matcher from src.plugins.nonebot_plugin_heweather, type=message, priority=1, temp=False>
          └ <function _run_matcher at 0x7f7416e94280>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0x7f7419095d30>: <Task finished name='Task-197340' coro=<_command() done, defined at /usr/local/python...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7f73d86dc610>
          │       │   │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None}, '_matched': '深圳天气', '_matched_groups': ('深圳',), '_ma...
          │       │   │    └ GroupMessageEvent(time=1646230388, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f73f4fc9d30>
          │       └ <function Matcher.run at 0x7f7419095790>
          └ <Matcher from src.plugins.nonebot_plugin_heweather, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0x7f7419095d30>: <Task finished name='Task-197340' coro=<_command() done, defined at /usr/local/python...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7f73d86dc610>
          │    │          │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None}, '_matched': '深圳天气', '_matched_groups': ('深圳',), '_ma...
          │    │          │    └ GroupMessageEvent(time=1646230388, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f73f4fc9d30>
          │    └ <function Matcher.simple_run at 0x7f7419095700>
          └ <Matcher from src.plugins.nonebot_plugin_heweather, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function _ at 0x7f73f746dee0>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='eve...
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'bot': <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f73f4fc9d30>, 'event': GroupMessageEvent(time=1646230388, self_id=5...
                 │    └ <function _ at 0x7f73f746dee0>
                 └ <Dependent call=<function _ at 0x7f73f746dee0>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='eve...

  File "./src/plugins/nonebot_plugin_heweather/__init__.py", line 35, in _
    img = await render(w_data)
                │      └ <src.plugins.nonebot_plugin_heweather.weather_data.Weather object at 0x7f73d8ba96d0>
                └ <function render at 0x7f73f746daf0>

  File "./src/plugins/nonebot_plugin_heweather/render_pic.py", line 11, in render
    return await template_to_pic(
                 └ <function template_to_pic at 0x7f740fda01f0>

  File "/usr/local/python3/lib/python3.8/site-packages/nonebot_plugin_htmlrender/date_source.py", line 194, in template_to_pic
    return await html_to_pic(
                 └ <function html_to_pic at 0x7f740fda0160>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot_plugin_htmlrender/date_source.py", line 159, in html_to_pic
    await page.goto(template_path)
          │    │    └ 'file://src/plugins/nonebot_plugin_heweather/templates'
          │    └ <function Page.goto at 0x7f7410084790>
          └ <Page url='about:blank'>
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 7516, in goto
    await self._async(
          │    └ <function AsyncBase._async at 0x7f74100c40d0>
          └ <Page url='about:blank'>
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_page.py", line 487, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
                 │    │           │      └ <function locals_to_params at 0x7f7410406e50>
                 │    │           └ <function Frame.goto at 0x7f741010ddc0>
                 │    └ <Frame name= url='about:blank'>
                 └ <Page url='about:blank'>
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_frame.py", line 122, in goto
    await self._channel.send("goto", locals_to_params(locals()))
          │    │        │            └ <function locals_to_params at 0x7f7410406e50>
          │    │        └ <function Channel.send at 0x7f7410197e50>
          │    └ <playwright._impl._connection.Channel object at 0x7f73d8697250>
          └ <Frame name= url='about:blank'>
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
                 │    │          │       └ {'url': 'file://src/plugins/nonebot_plugin_heweather/templates'}
                 │    │          └ 'goto'
                 │    └ <function Channel.inner_send at 0x7f7410197f70>
                 └ <playwright._impl._connection.Channel object at 0x7f73d8697250>
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
                       └ {<Future finished exception=Error('net::ERR_INVALID_URL at file://src/plugins/nonebot_plugin_heweather/templates\n===========...

playwright._impl._api_types.Error: net::ERR_INVALID_URL at file://src/plugins/nonebot_plugin_heweather/templates
=========================== logs ===========================
navigating to "file://src/plugins/nonebot_plugin_heweather/templates", waiting until "load"
============================================================
[36mATRI[0m | 03-02 22:13:10 | ERROR nonebot >> Error when running RunPostProcessors
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f741ff2e040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f74280a2130>
         │    └ <function MultiCommand.invoke at 0x7f741ff320d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f74280a7ca0>
           │               │       │       └ <function Command.invoke at 0x7f741ff2eaf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7f74280a7ca0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f742077aa60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7f74280a7ca0>
           │   │      │    └ <function run at 0x7f7416f7a5e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7f74201ab8b0>
           └ <click.core.Context object at 0x7f74280a7ca0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7f7416f6a3a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7f7419073550>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7f74190730d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7f7416d76280>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7f7416d76670>
    └ <uvicorn.server.Server object at 0x7f73f5c125e0>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f7416d76700>
           │       │   └ <uvicorn.server.Server object at 0x7f73f5c125e0>
           │       └ <function run at 0x7f741c7c10d0>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f73f5c52740>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 227, in _run_matcher
    await asyncio.gather(*coros)
          │       │       └ [<coroutine object _run_coro_with_catch at 0x7f73d85af040>]
          │       └ <function gather at 0x7f741a5e5c10>
          └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 115, in _run_coro_with_catch
    return await coro
                 └ <coroutine object Dependent.__call__ at 0x7f73d8ba23c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'exception': Error('net::ERR_INVALID_URL at file://src/plugins/nonebot_plugin_heweather/templates\n=========================...
                 │    └ <function _track_error at 0x7f73f75e04c0>
                 └ <Dependent call=<function _track_error at 0x7f73f75e04c0>, params=[ModelField(name='exception', type=Optional[Exception], req...
  File "/usr/local/python3/lib/python3.8/site-packages/ATRI/exceptions.py", line 115, in _track_error
    await bot.send_private_msg(user_id=superusers, message=msg)
          │                            │                   └ '呜——出错了...追踪: OiETI9oN'
          │                            └ '1234567890'
          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f73f4fc9d30>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/bot.py", line 208, in call_api
    return await super().call_api(api, **data)
                                  │      └ {'user_id': '1234567890', 'message': '呜——出错了...追踪: OiETI9oN'}
                                  └ 'send_private_msg'
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 117, in call_api
    raise exception
          └ <ActionFailed data=None, echo={'seq': 49}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
                   │    │       │         │     │      └ {'user_id': '1234567890', 'message': '呜——出错了...追踪: OiETI9oN'}
                   │    │       │         │     └ 'send_private_msg'
                   │    │       │         └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f73f4fc9d30>
                   │    │       └ <function Adapter._call_api at 0x7f7416e94b80>
                   │    └ <nonebot.adapters.onebot.v11.adapter.Adapter object at 0x7f7416f81820>
                   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f73f4fc9d30>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 107, in _call_api
    return _handle_api_result(
           └ <function _handle_api_result at 0x7f7416f22310>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/utils.py", line 81, in _handle_api_result
    raise ActionFailed(**result)
          │              └ {'data': None, 'echo': {'seq': 49}, 'msg': 'SEND_MSG_API_ERROR', 'retcode': 100, 'status': 'failed', 'wording': '请参考 go-cqhtt...
          └ <class 'nonebot.adapters.onebot.v11.exception.ActionFailed'>

nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 49}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
[36mATRI[0m | 03-02 22:13:18 | ERROR nonebot >> Running matcher <Matcher from src.plugins.nonebot_plugin_heweather, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f741ff2e040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f74280a2130>
         │    └ <function MultiCommand.invoke at 0x7f741ff320d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f74280a7ca0>
           │               │       │       └ <function Command.invoke at 0x7f741ff2eaf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7f74280a7ca0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f742077aa60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7f74280a7ca0>
           │   │      │    └ <function run at 0x7f7416f7a5e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7f74201ab8b0>
           └ <click.core.Context object at 0x7f74280a7ca0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7f7416f6a3a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7f7419073550>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7f74190730d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7f7416d76280>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7f7416d76670>
    └ <uvicorn.server.Server object at 0x7f73f5c125e0>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f7416d76700>
           │       │   └ <uvicorn.server.Server object at 0x7f73f5c125e0>
           │       └ <function run at 0x7f741c7c10d0>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f73f5c52740>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0x7f7419095d30>: <Task finished name='Task-197722' coro=<_command() done, defined at /usr/local/python...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7f73d8640100>
          │            │        │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None}, '_matched': '/深圳天气', '_matched_groups': ('/深圳',), '_...
          │            │        │    └ GroupMessageEvent(time=1646230397, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │            │        └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f73f4fc9d30>
          │            └ <Matcher from src.plugins.nonebot_plugin_heweather, type=message, priority=1, temp=False>
          └ <function _run_matcher at 0x7f7416e94280>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0x7f7419095d30>: <Task finished name='Task-197722' coro=<_command() done, defined at /usr/local/python...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7f73d8640100>
          │       │   │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None}, '_matched': '/深圳天气', '_matched_groups': ('/深圳',), '_...
          │       │   │    └ GroupMessageEvent(time=1646230397, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f73f4fc9d30>
          │       └ <function Matcher.run at 0x7f7419095790>
          └ <Matcher from src.plugins.nonebot_plugin_heweather, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0x7f7419095d30>: <Task finished name='Task-197722' coro=<_command() done, defined at /usr/local/python...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7f73d8640100>
          │    │          │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None}, '_matched': '/深圳天气', '_matched_groups': ('/深圳',), '_...
          │    │          │    └ GroupMessageEvent(time=1646230397, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f73f4fc9d30>
          │    └ <function Matcher.simple_run at 0x7f7419095700>
          └ <Matcher from src.plugins.nonebot_plugin_heweather, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function _ at 0x7f73f746dee0>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='eve...
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'bot': <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f73f4fc9d30>, 'event': GroupMessageEvent(time=1646230397, self_id=5...
                 │    └ <function _ at 0x7f73f746dee0>
                 └ <Dependent call=<function _ at 0x7f73f746dee0>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='eve...

  File "./src/plugins/nonebot_plugin_heweather/__init__.py", line 35, in _
    img = await render(w_data)
                │      └ <src.plugins.nonebot_plugin_heweather.weather_data.Weather object at 0x7f73d8b9fdc0>
                └ <function render at 0x7f73f746daf0>

  File "./src/plugins/nonebot_plugin_heweather/render_pic.py", line 11, in render
    return await template_to_pic(
                 └ <function template_to_pic at 0x7f740fda01f0>

  File "/usr/local/python3/lib/python3.8/site-packages/nonebot_plugin_htmlrender/date_source.py", line 194, in template_to_pic
    return await html_to_pic(
                 └ <function html_to_pic at 0x7f740fda0160>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot_plugin_htmlrender/date_source.py", line 159, in html_to_pic
    await page.goto(template_path)
          │    │    └ 'file://src/plugins/nonebot_plugin_heweather/templates'
          │    └ <function Page.goto at 0x7f7410084790>
          └ <Page url='about:blank'>
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 7516, in goto
    await self._async(
          │    └ <function AsyncBase._async at 0x7f74100c40d0>
          └ <Page url='about:blank'>
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_page.py", line 487, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
                 │    │           │      └ <function locals_to_params at 0x7f7410406e50>
                 │    │           └ <function Frame.goto at 0x7f741010ddc0>
                 │    └ <Frame name= url='about:blank'>
                 └ <Page url='about:blank'>
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_frame.py", line 122, in goto
    await self._channel.send("goto", locals_to_params(locals()))
          │    │        │            └ <function locals_to_params at 0x7f7410406e50>
          │    │        └ <function Channel.send at 0x7f7410197e50>
          │    └ <playwright._impl._connection.Channel object at 0x7f73d8ba46d0>
          └ <Frame name= url='about:blank'>
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
                 │    │          │       └ {'url': 'file://src/plugins/nonebot_plugin_heweather/templates'}
                 │    │          └ 'goto'
                 │    └ <function Channel.inner_send at 0x7f7410197f70>
                 └ <playwright._impl._connection.Channel object at 0x7f73d8ba46d0>
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
                       └ {<Future finished exception=Error('net::ERR_INVALID_URL at file://src/plugins/nonebot_plugin_heweather/templates\n===========...

playwright._impl._api_types.Error: net::ERR_INVALID_URL at file://src/plugins/nonebot_plugin_heweather/templates
=========================== logs ===========================
navigating to "file://src/plugins/nonebot_plugin_heweather/templates", waiting until "load"
============================================================
[36mATRI[0m | 03-02 22:13:18 | ERROR nonebot >> Error when running RunPostProcessors
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f741ff2e040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f74280a2130>
         │    └ <function MultiCommand.invoke at 0x7f741ff320d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f74280a7ca0>
           │               │       │       └ <function Command.invoke at 0x7f741ff2eaf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7f74280a7ca0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f742077aa60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7f74280a7ca0>
           │   │      │    └ <function run at 0x7f7416f7a5e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7f74201ab8b0>
           └ <click.core.Context object at 0x7f74280a7ca0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7f7416f6a3a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7f7419073550>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7f74190730d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7f7416d76280>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7f7416d76670>
    └ <uvicorn.server.Server object at 0x7f73f5c125e0>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f7416d76700>
           │       │   └ <uvicorn.server.Server object at 0x7f73f5c125e0>
           │       └ <function run at 0x7f741c7c10d0>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f73f5c52740>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 227, in _run_matcher
    await asyncio.gather(*coros)
          │       │       └ [<coroutine object _run_coro_with_catch at 0x7f73d86c69c0>]
          │       └ <function gather at 0x7f741a5e5c10>
          └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 115, in _run_coro_with_catch
    return await coro
                 └ <coroutine object Dependent.__call__ at 0x7f73d86e2240>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'exception': Error('net::ERR_INVALID_URL at file://src/plugins/nonebot_plugin_heweather/templates\n=========================...
                 │    └ <function _track_error at 0x7f73f75e04c0>
                 └ <Dependent call=<function _track_error at 0x7f73f75e04c0>, params=[ModelField(name='exception', type=Optional[Exception], req...
  File "/usr/local/python3/lib/python3.8/site-packages/ATRI/exceptions.py", line 115, in _track_error
    await bot.send_private_msg(user_id=superusers, message=msg)
          │                            │                   └ '呜——出错了...追踪: yr1Kagb0'
          │                            └ '1234567890'
          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f73f4fc9d30>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/bot.py", line 208, in call_api
    return await super().call_api(api, **data)
                                  │      └ {'user_id': '1234567890', 'message': '呜——出错了...追踪: yr1Kagb0'}
                                  └ 'send_private_msg'
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 117, in call_api
    raise exception
          └ <ActionFailed data=None, echo={'seq': 50}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
                   │    │       │         │     │      └ {'user_id': '1234567890', 'message': '呜——出错了...追踪: yr1Kagb0'}
                   │    │       │         │     └ 'send_private_msg'
                   │    │       │         └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f73f4fc9d30>
                   │    │       └ <function Adapter._call_api at 0x7f7416e94b80>
                   │    └ <nonebot.adapters.onebot.v11.adapter.Adapter object at 0x7f7416f81820>
                   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f73f4fc9d30>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 107, in _call_api
    return _handle_api_result(
           └ <function _handle_api_result at 0x7f7416f22310>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/utils.py", line 81, in _handle_api_result
    raise ActionFailed(**result)
          │              └ {'data': None, 'echo': {'seq': 50}, 'msg': 'SEND_MSG_API_ERROR', 'retcode': 100, 'status': 'failed', 'wording': '请参考 go-cqhtt...
          └ <class 'nonebot.adapters.onebot.v11.exception.ActionFailed'>

nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 50}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
