{
    "track_id": "IoHNurDk",
    "prompt": "Unknown ERROR->Error",
    "time": "2022-03-13 17:37:43",
    "content": "Traceback (most recent call last):\n  File \"/usr/local/python3/lib/python3.8/site-packages/ATRI/exceptions.py\", line 102, in _track_error\n    raise exception\n  File \"/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py\", line 202, in _run_matcher\n    await matcher.run(bot, event, state, stack, dependency_cache)\n  File \"/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py\", line 668, in run\n    await self.simple_run(bot, event, state, stack, dependency_cache)\n  File \"/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py\", line 635, in simple_run\n    await handler(\n  File \"/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py\", line 92, in __call__\n    return await self.call(**values)\n  File \"./src/plugins/nonebot_plugin_heweather/__init__.py\", line 35, in _\n    img = await render(w_data)\n  File \"./src/plugins/nonebot_plugin_heweather/render_pic.py\", line 11, in render\n    return await template_to_pic(\n  File \"/usr/local/python3/lib/python3.8/site-packages/nonebot_plugin_htmlrender/date_source.py\", line 194, in template_to_pic\n    return await html_to_pic(\n  File \"/usr/local/python3/lib/python3.8/site-packages/nonebot_plugin_htmlrender/date_source.py\", line 159, in html_to_pic\n    await page.goto(template_path)\n  File \"/usr/local/python3/lib/python3.8/site-packages/playwright/async_api/_generated.py\", line 7516, in goto\n    await self._async(\n  File \"/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_page.py\", line 487, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n  File \"/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_frame.py\", line 122, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_connection.py\", line 39, in send\n    return await self.inner_send(method, params, False)\n  File \"/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_connection.py\", line 63, in inner_send\n    result = next(iter(done)).result()\nplaywright._impl._api_types.Error: net::ERR_INVALID_URL at file://src/plugins/nonebot_plugin_heweather/templates\n=========================== logs ===========================\nnavigating to \"file://src/plugins/nonebot_plugin_heweather/templates\", waiting until \"load\"\n============================================================\n"
}