{
    "track_id": "Oz0Va2F3",
    "prompt": "Unknown ERROR->KeyError",
    "time": "2022-03-09 14:29:04",
    "content": "Traceback (most recent call last):\n  File \"/usr/local/python3/lib/python3.8/site-packages/ATRI/exceptions.py\", line 102, in _track_error\n    raise exception\n  File \"/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py\", line 202, in _run_matcher\n    await matcher.run(bot, event, state, stack, dependency_cache)\n  File \"/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py\", line 668, in run\n    await self.simple_run(bot, event, state, stack, dependency_cache)\n  File \"/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py\", line 635, in simple_run\n    await handler(\n  File \"/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py\", line 92, in __call__\n    return await self.call(**values)\n  File \"./src/plugins/nonebot_plugin_russian/__init__.py\", line 368, in _\n    russian_manager._earn_data_handle(int(args[0]), event.group_id, int(args[1]))\n  File \"./src/plugins/nonebot_plugin_russian/data_source.py\", line 635, in _earn_data_handle\n    self._player_data[group_id][user_id][\"gold\"] += money\nKeyError: '-8000'\n"
}