{
    "track_id": "qw1doIpL",
    "prompt": "Unknown ERROR->AttributeError",
    "time": "2022-03-02 21:28:43",
    "content": "Traceback (most recent call last):\n  File \"/usr/local/python3/lib/python3.8/site-packages/ATRI/exceptions.py\", line 102, in _track_error\n    raise exception\n  File \"/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py\", line 202, in _run_matcher\n    await matcher.run(bot, event, state, stack, dependency_cache)\n  File \"/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py\", line 668, in run\n    await self.simple_run(bot, event, state, stack, dependency_cache)\n  File \"/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py\", line 635, in simple_run\n    await handler(\n  File \"/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py\", line 92, in __call__\n    return await self.call(**values)\n  File \"./src/plugins/nonebot_plugin_status/__init__.py\", line 64, in server_status\n    pic = await md_to_pic(md=data)\n  File \"./src/plugins/nonebot_plugin_status/data_source.py\", line 75, in md_to_pic\n    md = markdown.markdown(\n  File \"/usr/local/python3/lib/python3.8/site-packages/markdown/core.py\", line 387, in markdown\n    return md.convert(text)\n  File \"/usr/local/python3/lib/python3.8/site-packages/markdown/core.py\", line 248, in convert\n    if not source.strip():\nAttributeError: 'list' object has no attribute 'strip'\n"
}