{
    "track_id": "tldG7m23",
    "prompt": "Unknown ERROR->TypeError",
    "time": "2022-03-04 17:50:50",
    "content": "Traceback (most recent call last):\n  File \"/usr/local/python3/lib/python3.8/site-packages/ATRI/exceptions.py\", line 102, in _track_error\n    raise exception\n  File \"/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py\", line 202, in _run_matcher\n    await matcher.run(bot, event, state, stack, dependency_cache)\n  File \"/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py\", line 668, in run\n    await self.simple_run(bot, event, state, stack, dependency_cache)\n  File \"/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py\", line 635, in simple_run\n    await handler(\n  File \"/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py\", line 92, in __call__\n    return await self.call(**values)\n  File \"./src/plugins/nonebot_plugin_russian/__init__.py\", line 432, in _\n    money_per_stock = russian_manager._check_stock_handle()[\"money_per_stock\"]\nTypeError: _check_stock_handle() takes 0 positional arguments but 1 was given\n"
}